layout_spectrum: 0.2723404
typography_spectrum: 0.8085107
color:
  lightness: 0.2774927
  brandStrength: 0.141846
  saturation: 0.7113941
  rhythmicContrast: 0.2710176
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Goat
