name: Goat
favicon: null
layout_spectrum: 0.2723404
typography_spectrum: 0.8085107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.141846
  lightness: 0.2774927
  saturation: 0.7113941
  rhythmicContrast: 0.2710176
purpose: []
